STATUS_UPDATE_URL = "https://api.twitter.com/1.1/statuses/update.json"
SEARCH_TWEET_URL = "https://api.twitter.com/1.1/search/tweets.json"
RETWEET_URL = "https://api.twitter.com/1.1/statuses/retweet/{}.json"
FAVORITE_URL = "https://api.twitter.com/1.1/favorites/create.json"
MENTION_TIMELINE_URL = "https://api.twitter.com/1.1/statuses/mentions_timeline.json"
USER_TIMELINE_URL = "https://api.twitter.com/1.1/statuses/user_timeline.json"
FOLLOW_URL = "https://api.twitter.com/1.1/friendships/create.json"
GET_FOLLOWER_URL = "https://api.twitter.com/1.1/followers/ids.json"